# These are supported funding model platforms

github: # [thindery] # Replace with your GitHub username
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
